format_version: 10
pipelines:
  build:
    group: graphql-springboot-yaml-pipeline
    label_template: ${COUNT}
    materials:
      graphql-springboot-repo:
        git: https://github.com/diegogomesaraujo/graphql-springboot.git
        branch: master
    stages:
      - build:
          fetch_materials: true
          keep_artifacts: false
          clean_workspace: false
          jobs:
            package:
              resources:
                - maven
              tasks:
                - exec:
                    command: mvn
                    arguments:
                      - clean
                      - package
                      - -DskipTests
      - build_image:
          fetch_materials: false
          approval:
            type: success
            allow_only_on_success: true
          jobs:
            build:
              resources:
                - docker
              tasks:
                - exec:
                    command: sh
                    arguments:
                      - -c
                      - docker build -t $GO_PIPELINE_NAME:$GO_PIPELINE_LABEL .
      - deploy_qa:
          fetch_materials: false
          approval:
            type: manual
            allow_only_on_success: true
          jobs:
            stop:
              tasks:
                - exec:
                  command: docker
                  arguments:
                    - container
                    - rm
                    - -rf
                    - $GO_PIPELINE_NAME
            start:
              tasks:
                - exec:
                    command: docker
                    arguments:
                      - container
                      - run
                      - -d
                      - --name
                      - $GO_PIPELINE_NAME
                      - $GO_PIPELINE_NAME:$GO_PIPELINE_LABEL