format_version: 9
pipelines:
  build:
    group: graphql-springboot-yaml-pipeline
    label_template: ${COUNT}
    materials:
      repo:
        git: https://github.com/diegogomesaraujo/graphql-springboot
        branch: master
    stages:
      - build:
        clean_workspace: false
        fetch_materials: yes
        jobs:
          build:
            resources:
              - maven
            tasks:
              - exec:
                command: mvn
                arguments:
                  - clean
                  - package
                  - -DskipTests
      - build_image:
        fetch_materials: no
        jobs:
          build:
            resources:
              - docker
            tasks:
              - exec:
                command: sh
                arguments:
                  - -c
                  - docker build -t $GO_PIPELINE_NAME:$GO_PIPELINE_LABEL .