format_version: 10
pipelines:
  hello-world-build:
    group: hello-world
    display_order: 1
    materials:
      repo:
        git: https://github.com/diegogomesaraujo/hello-pipeline-agocd-argocd.git
        branch: master
    stages:
      - build:
          fetch_materials: true
          keep_artifacts: true
          clean_workspace: false
          jobs:
            build:
              resources:
                - maven
              artifacts:
                - build:
                    source: target/*.jar
                    destination: artifacts
              tasks:
                - exec:
                    command: sh
                    arguments:
                      - -c
                      - mvn clean package
      - build-image:
          fetch_materials: false
          resource:
            - docker
          tasks:
            # - fetch:
            #     # pipeline: hello-world-build
            #     stage: build
            #     job: build
            #     source: artifacts/
            #     destination: ''
            - exec:
                command: sh
                arguments:
                  - -c
                  - ls -lh artifacts
            - exec:
                command: /bin/bash
                arguments:
                  - ops/build.sh