format_version: 10
pipelines:
  hello-world-build:
    group: hello-world
    display_order: 1
    materials:
      repo:
        git: https://github.com/diegogomesaraujo/hello-pipeline-agocd-argocd.git
        branch: master
    stages:
      - build:
          fetch_materials: true
          keep_artifacts: true
          clean_workspace: false
          jobs:
            build:
              resources:
                - maven
              artifacts:
                - build:
                    source: target/
                    destination: build
              tasks:
                - exec:
                    command: /bin/bash
                    arguments:
                      - ops/build.sh
    hello-world-deploy:
      group: hello-world
      display_order: 2
      stages:
        - deploy:
            fetch_materials: true
            keep_artifacts: true
            clean_workspace: false
            jobs:
              deploy:
                resource:
                  - docker
                tasks:
                  - fetch:
                      pipeline: hello-world-build
                      stage: build
                      job: build
                      source: build/
                      destination: ''
                  - exec:
                      command: /bin/bash
                      arguments:
                        - ops/deploy.sh